### ISSUE TITLE
[2.0.0-beta4] Fatal Exception: java.lang.NullPointerException Attempt to invoke virtual method 'java.lang.String org.jivesoftware.smack.AbstractXMPPConnection.getUser()' on a null object reference com.cometchat.pro.core.XMPPConnectionService.subscribeToNode

### ISSUE THREAD

**Issue by aldy-deptech** [cometchat-pro/android-chat-sdk#24] opened 2020-01-13 04:35 UTC
Describe the bug
When connecting / login to cometchat

To Reproduce
com.cometchat.pro.core.XMPPConnectionService.subscribeToNode (XMPPConnectionService.java:441)
com.cometchat.pro.core.XMPPConnectionService.handlePresenceSubscriptions (XMPPConnectionService.java:404)
com.cometchat.pro.core.XMPPConnectionService.access$1200 (XMPPConnectionService.java:100)
com.cometchat.pro.core.XMPPConnectionService$8.run (XMPPConnectionService.java:332)
java.lang.Thread.run (Thread.java:762)

Expected behavior
cometchat will be connect / logged

Actual behavior
force close / crash

Enviorment/Platfrom (please complete the following information):

Android 9 (API 28)
Cometchat version is 2.0.0-beta4

Logs (Error Logs)
com.cometchat.pro.core.XMPPConnectionService.subscribeToNode (XMPPConnectionService.java:441)
com.cometchat.pro.core.XMPPConnectionService.handlePresenceSubscriptions (XMPPConnectionService.java:404)
com.cometchat.pro.core.XMPPConnectionService.access$1200 (XMPPConnectionService.java:100)
com.cometchat.pro.core.XMPPConnectionService$8.run (XMPPConnectionService.java:332)
java.lang.Thread.run (Thread.java:762)

**Comment by adityagokula2210** [comment] 2020-01-13 08:02
As mentioned in issue #23, we have fixed this issue in  version 2.0.2 of the Android SDK, 
The cause of the issue is the same as mentioned in #23 
We are closing this issue so as to have a single point of communication regarding the issue and any further communication can be taken up on #23 
Hope this helps

**Closed as completed by adityagokula2210** 2020-01-13 08:02 UTC
