### ISSUE TITLE
Hello Comet, I am facing problem sometimes while using your Chat SDK. Please check this error and let us know.

### ISSUE THREAD

**Issue by sushil-kumr** [cometchat-pro/android-chat-sdk#12] opened 2019-09-09 11:43 UTC
2019-09-09 17:04:43.337 11366-11366/co.speakto.advisor E/ActivityThread: Activity co.speakto.advisor.Activities.ChatActivity has leaked IntentReceiver com.cometchat.pro.core.NetworkChangeReceiver@9c5b6d3 that was originally registered here. Are you missing a call to unregisterReceiver()?
    android.app.IntentReceiverLeaked: Activity co.speakto.advisor.Activities.ChatActivity has leaked IntentReceiver com.cometchat.pro.core.NetworkChangeReceiver@9c5b6d3 that was originally registered here. Are you missing a call to unregisterReceiver()?
        at android.app.LoadedApk$ReceiverDispatcher.<init>(LoadedApk.java:1159)
        at android.app.LoadedApk.getReceiverDispatcher(LoadedApk.java:946)
        at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1330)
        at android.app.ContextImpl.registerReceiver(ContextImpl.java:1310)
        at android.app.ContextImpl.registerReceiver(ContextImpl.java:1304)
        at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:586)
        at com.cometchat.pro.core.CometChat.<init>(CometChat.java:437)
        at com.cometchat.pro.core.CometChat.init(CometChat.java:406)
        at co.speakto.advisor.Activities.ChatActivity.onCreate(ChatActivity.java:101)
        at android.app.Activity.performCreate(Activity.java:6672)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1140)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2612)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2724)
        at android.app.ActivityThread.-wrap12(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1473)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6123)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)

**Comment by adityagokula2210** [comment] 2019-11-04 11:00
Unable to reproduce. 
Closing the issue as the issue was not replicated at our end.

**Closed as completed by adityagokula2210** 2019-11-04 11:00 UTC
